-- ============================================================
-- ZERO HUNGER P2P NETWORK — FULL DATABASE REINITIALISATION
-- Run this entire file in the Supabase SQL Editor
-- ============================================================

-- ============================================================
-- STEP 1: CLEAN UP (drop old objects if they exist)
-- ============================================================

-- Drop functions (CASCADE removes attached triggers automatically)
DROP FUNCTION IF EXISTS update_lifetime_stats() CASCADE;
DROP FUNCTION IF EXISTS check_handoff_completion() CASCADE;

-- Drop tables in safe dependency order
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS platform_stats CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS fund_requests CASCADE;
DROP TABLE IF EXISTS trusts CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS donations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- STEP 2: CREATE TABLES
-- ============================================================

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  UNIQUE NOT NULL,
    password    VARCHAR(255) NOT NULL,
    name        VARCHAR(100),
    email       VARCHAR(100),
    phone       VARCHAR(20),
    role        VARCHAR(20)  DEFAULT 'user',
    emoji       VARCHAR(10),
    profile_image_url VARCHAR(255),
    created_at  TIMESTAMPTZ  DEFAULT NOW()
);

CREATE TABLE donations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_username   VARCHAR(50),
    donor_name       VARCHAR(100),
    food_name        VARCHAR(100),
    food_type        VARCHAR(50),
    quantity         INT,
    mfg_date         DATE,
    expiry_date      DATE,
    location_label   VARCHAR(255),
    lat              DECIMAL(10, 8),
    lng              DECIMAL(11, 8),
    freshness_score  DECIMAL(3, 1),
    expiry_days      INT,
    pay_type         VARCHAR(20),
    pay_info         VARCHAR(255),
    status           VARCHAR(20) DEFAULT 'available',
    image_url        VARCHAR(255),
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_username      VARCHAR(50),
    req_name          VARCHAR(100),
    donation_id       BIGINT REFERENCES donations(id) ON DELETE CASCADE,
    food_name         VARCHAR(100),
    quantity          INT,
    urgency           VARCHAR(20),
    location_label    VARCHAR(255),
    priority_score    INT,
    distance_km       DECIMAL(5, 2),
    status            VARCHAR(20) DEFAULT 'pending',
    donor_confirmed   BOOLEAN DEFAULT FALSE,
    receiver_confirmed BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE volunteers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vol_username     VARCHAR(50),
    vol_name         VARCHAR(100),
    vehicle_type     VARCHAR(50),
    pickup_location  VARCHAR(255),
    shift            VARCHAR(20),
    time_slot        VARCHAR(50),
    status           VARCHAR(20) DEFAULT 'active',
    assigned_req_id  BIGINT REFERENCES requests(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ratings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_username  VARCHAR(50),
    category         VARCHAR(50),
    score            INT,
    review           TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE trusts (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trust_username        VARCHAR(50) UNIQUE NOT NULL,
    trust_name            VARCHAR(100),
    contact_email         VARCHAR(100),
    contact_phone         VARCHAR(20),
    cert_image_url        TEXT,
    verification_status   VARCHAR(20) DEFAULT 'pending',
    created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE fund_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trust_username VARCHAR(50),
    trust_name     VARCHAR(100),
    amount         DECIMAL(10, 2),
    purpose        VARCHAR(255),
    upi_id         VARCHAR(100),
    status         VARCHAR(20) DEFAULT 'open',
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_username   VARCHAR(50) NOT NULL,
    receiver_username VARCHAR(50) NOT NULL,
    context_type      VARCHAR(50),
    context_id        BIGINT,
    message_text      TEXT NOT NULL,
    is_read           BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username VARCHAR(50),
    message       TEXT NOT NULL,
    urgency       VARCHAR(20) DEFAULT 'Normal',
    is_read       BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE platform_stats (
    id                   INT PRIMARY KEY DEFAULT 1,
    total_donations      INT DEFAULT 0,
    total_meals_saved    INT DEFAULT 0,
    total_freshness_score DECIMAL(10, 2) DEFAULT 0
);

-- Seed the single stats row
INSERT INTO platform_stats (id, total_donations, total_meals_saved, total_freshness_score)
VALUES (1, 0, 0, 0);

-- ============================================================
-- STEP 3: TRIGGERS & FUNCTIONS
-- ============================================================

-- ---- 3a: Lifetime Stats — fires on every new donation ----
CREATE OR REPLACE FUNCTION update_lifetime_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE platform_stats SET
        total_donations       = total_donations + 1,
        total_meals_saved     = total_meals_saved + ROUND(NEW.quantity * 0.8),
        total_freshness_score = total_freshness_score + COALESCE(NEW.freshness_score, 0)
    WHERE id = 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_stats
AFTER INSERT ON donations
FOR EACH ROW
EXECUTE FUNCTION update_lifetime_stats();

-- ---- 3b: Dual-Confirmation Handoff — fires on request confirm update ----
CREATE OR REPLACE FUNCTION check_handoff_completion()
RETURNS TRIGGER AS $$
DECLARE
    don_qty INT;
BEGIN
    -- Only act when BOTH sides are confirmed
    IF NEW.donor_confirmed = TRUE AND NEW.receiver_confirmed = TRUE THEN

        SELECT quantity INTO don_qty FROM donations WHERE id = NEW.donation_id;

        IF don_qty <= NEW.quantity THEN
            -- Donor stock fully consumed: delete entire donation (cascades to request)
            DELETE FROM donations WHERE id = NEW.donation_id;
        ELSE
            -- Partial fulfillment: deduct quantity, delete only this request
            UPDATE donations
               SET quantity = quantity - NEW.quantity
             WHERE id = NEW.donation_id;

            DELETE FROM requests WHERE id = NEW.id;
        END IF;

        -- Notify both parties
        INSERT INTO notifications (user_username, message, urgency)
        VALUES
            (NEW.req_username, '✅ Food handoff confirmed! Thank you for receiving.', 'Normal'),
            ((SELECT donor_username FROM donations WHERE id = NEW.donation_id),
             '✅ Delivery confirmed! Your contribution is recorded.', 'Normal');

        RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_check_handoff
AFTER UPDATE OF donor_confirmed, receiver_confirmed ON requests
FOR EACH ROW
EXECUTE FUNCTION check_handoff_completion();

-- ============================================================
-- STEP 4: AUTO-EXPIRY CRON JOB
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pg_cron;

SELECT cron.schedule(
    'delete-expired-donations',
    '0 0 * * *',
    $$ DELETE FROM donations WHERE expiry_date < CURRENT_DATE; $$
);

-- ============================================================
-- STEP 5: STORAGE BUCKETS (idempotent — safe to re-run)
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('food-images', 'food-images', true)
ON CONFLICT (id) DO NOTHING;

-- Public read policies
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects' AND policyname = 'Public Access to Avatars'
    ) THEN
        EXECUTE 'CREATE POLICY "Public Access to Avatars" ON storage.objects FOR SELECT USING (bucket_id = ''avatars'')';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'objects' AND policyname = 'Public Access to Food Images'
    ) THEN
        EXECUTE 'CREATE POLICY "Public Access to Food Images" ON storage.objects FOR SELECT USING (bucket_id = ''food-images'')';
    END IF;
END $$;

-- ============================================================
-- STEP 6: DISABLE ROW LEVEL SECURITY (Allows Anon Key Read/Write)
-- ============================================================
ALTER TABLE donations        DISABLE ROW LEVEL SECURITY;
ALTER TABLE requests         DISABLE ROW LEVEL SECURITY;
ALTER TABLE users            DISABLE ROW LEVEL SECURITY;
ALTER TABLE volunteers       DISABLE ROW LEVEL SECURITY;
ALTER TABLE ratings          DISABLE ROW LEVEL SECURITY;
ALTER TABLE trusts           DISABLE ROW LEVEL SECURITY;
ALTER TABLE fund_requests    DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages         DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications    DISABLE ROW LEVEL SECURITY;
ALTER TABLE platform_stats   DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- DONE — Database is fully initialised.
-- ============================================================
