-- Supabase PostgreSQL Schema for Zero Hunger P2P Network

CREATE TABLE Users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    age INT,
    email VARCHAR(100),
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'user',
    emoji VARCHAR(10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE Donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_username VARCHAR(50),
    donor_name VARCHAR(100),
    donor_age INT,
    food_name VARCHAR(100),
    food_type VARCHAR(50),
    quantity INT,
    mfg_date DATE,
    expiry_date DATE,
    location_label VARCHAR(255),
    lat DECIMAL(10, 8),
    lng DECIMAL(11, 8),
    freshness_score DECIMAL(3, 1),
    expiry_days INT,
    pay_type VARCHAR(20),
    pay_info VARCHAR(255),
    status VARCHAR(20) DEFAULT 'available',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE Requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_username VARCHAR(50),
    req_name VARCHAR(100),
    req_age INT,
    donation_id BIGINT REFERENCES Donations(id) ON DELETE CASCADE,
    food_name VARCHAR(100),
    quantity INT,
    urgency VARCHAR(20),
    location_label VARCHAR(255),
    priority_score INT,
    distance_km DECIMAL(5, 2),
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE Volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vol_username VARCHAR(50),
    vol_name VARCHAR(100),
    vol_age INT,
    vehicle_type VARCHAR(50),
    pickup_location VARCHAR(255),
    shift VARCHAR(20),
    time_slot VARCHAR(50),
    status VARCHAR(20) DEFAULT 'active',
    assigned_req_id BIGINT REFERENCES Requests(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE Ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_username VARCHAR(50),
    category VARCHAR(50),
    score INT,
    review TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
